version: '3.7'

services:
  backend:
    image: swe573_backend:1.0.0
    build:
      context: ./backend
    restart: always
    command: >
      bash -c "python /backend/manage.py makemigrations && python /backend/manage.py migrate && python /backend/manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend:/backend

  db:
    image: postgres:11
    restart: always
    container_name: ${POSTGRESQL_CONTAINER_NAME}
    ports:
      - ${POSTGRESQL_PORTS}
    environment:
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_DB: ${POSTGRESQL_DB}
    volumes:
      - swe573_dbdata:/var/lib/postgresql/data

  frontend:
    image: swe573_frontend:1.0.0
    build:
      context: ./frontend
    stdin_open: true
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./frontend/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    
volumes:
  swe573_dbdata: